# Generated by Django 5.1.3 on 2024-11-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "id",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=2,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added", models.DateTimeField()),
            ],
        ),
    ]
