# Generated by Django 5.1.3 on 2024-11-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="added",
            field=models.DateTimeField(verbose_name="Date/Time Added"),
        ),
    ]
